#!/usr/bin/env bash
# Print the RLS statements that gate dashboard writes, with the live SIGNAL_INGEST_KEY
# substituted in.
#
# Why this exists: brain.sql ships with `<PASTE SIGNAL_INGEST_KEY HERE>` on purpose — the key is a
# write credential and this repo is pushed to GitHub. But pasting brain.sql into the Supabase SQL
# editor with the placeholder left in silently creates a policy that compares the header against
# the literal string "<PASTE SIGNAL_INGEST_KEY HERE>", and every insert then fails with a 42501
# that looks like a code bug. That happened once. This script makes it impossible to repeat.
#
# Run on the VPS, copy the output into the Supabase SQL editor:
#
#     bash vps/render_ingest_policy.sh
#
# It also covers the stock engine's sd_scans / sd_signals policies, which inline the same key.
# Rotating the key means running all of these at once, or those older dashboards break.
#
# The output contains the secret. Paste it into Supabase only — never into a chat, an issue, or a
# commit.
set -euo pipefail

ENV_FILE="${SIGNAL_ENV:-/root/.secrets/signal.env}"
if [ -z "${SIGNAL_INGEST_KEY:-}" ] && [ -r "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  . "$ENV_FILE"
fi

if [ -z "${SIGNAL_INGEST_KEY:-}" ]; then
  echo "SIGNAL_INGEST_KEY not set and not found in $ENV_FILE" >&2
  exit 1
fi

cat <<SQL
-- Generated by vps/render_ingest_policy.sh — contains a live credential, do not commit.

-- Brain tables (sd_brain_scans, sd_brain_signals, sd_portfolio, sd_trades) go through this helper.
create or replace function public._brain_has_ingest_key() returns boolean
language sql stable as \$\$
  select coalesce(
    (current_setting('request.headers', true)::json ->> 'x-signal-key'),
    ''
  ) = '${SIGNAL_INGEST_KEY}'
\$\$;

-- Stock engine tables inline the key directly (tools/vps/dashboard.sql in the automation repo).
drop policy if exists "sd_scans write" on public.sd_scans;
create policy "sd_scans write" on public.sd_scans for insert to anon
  with check ((current_setting('request.headers', true)::json ->> 'x-signal-key')
              = '${SIGNAL_INGEST_KEY}');

drop policy if exists "sd_signals write" on public.sd_signals;
create policy "sd_signals write" on public.sd_signals for insert to anon
  with check ((current_setting('request.headers', true)::json ->> 'x-signal-key')
              = '${SIGNAL_INGEST_KEY}');
SQL
